### ISSUE TITLE
[Needs Grooming] validate decrypt works with attribute data 

### ISSUE THREAD

**Issue by cassandrabailey293** [opentdf/client-web#274]
there are some auth issues? maybe? needs investigation, grooming --

@dmihalcik-virtru can you validate whether or not we can decrypt with attribute data? we can close this ticket if this functionality works - otherwise if there is a bug we can groom this ticket to track the issue

**Comment by strantalis** [comment]
Duplicate of https://github.com/opentdf/client-web/issues/276
