### ISSUE TITLE
Readme should have valid links and instructions

### ISSUE THREAD

**Issue by jakedoublev** [opentdf/client-web#298]
There is doc drift in the readme (i.e. [the quickstart guide](https://github.com/opentdf/client-web#evaluate)) that is no longer in sync with the opentdf platform. The readme should be updated to point to the proper resources for documentation and instructions.

Related to https://github.com/opentdf/client-web/issues/271

**Comment by dmihalcik-virtru** [comment]
Closed with https://github.com/opentdf/client-web/pull/302
