### ISSUE TITLE
feat: attribute based key splits

### ISSUE THREAD

**Issue by strantalis** [opentdf/client-web#314]
With the introduction of attribute based key splitting in the go sdk. We now need to introduce this for ztdf in the javascript sdk. Implement the key splitting logic that was done in the go sdk and update x-tests to make
key splits generated with each sdk can interop.

**Comment by jrschumacher** [comment]
Dupe @jrschumacher find the dupe

**Comment by jrschumacher** [comment]
@dmihalcik-virtru will resolve the dupe and add the appropriate decomposition

- something with protos
- resize

**Comment by cassandrabailey293** [comment]
closing, work will continue in this issue - https://github.com/virtru-corp/data-security-platform/issues/606
