### ISSUE TITLE
limit manifest size

### ISSUE THREAD

**Issue by strantalis** [opentdf/client-web#345]
In the go sdk it was detected that a protocol attack could happen by reading an excessively large manifest. We should introduce the same limits within client-web.

Let's do a test that recreates the test done on the Go sdk, using a tdf with a large manifest, and observe the behavior in order to determine what is needed for this ticket. 

REF: https://github.com/opentdf/platform/pull/1385

Acceptance Criteria:

- Test to make sure a manifest isn't larger than 10mb

**Comment by dmihalcik-virtru** [comment]
My thinking now is that the maximum manifest size should be 10 MiB (for large policies) or about .01% the size of the payload (for very large payloads, which will in turn have a large number of segments)

**Comment by dmihalcik-virtru** [comment]
Either way, 10 MiB will be enough for files up to about 180 GiB or so so (with 2 MiB segments) I'll go ahead with the current fix
